version: '3'

services:
  tools:
    build:
      context: ./tools
      dockerfile: ./Dockerfile
    volumes:
      - ./scripts:/scripts
      - ./conf:/conf
      - ./pbf:/pbf
      - ./maps:/maps
    tty: true



